---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "eUDsNa9GR5Wr4qLBADzOXkek7PrCH1aXxkOGT2TiJrJPVEIxSIixDryT\
    rTwl8VsHvwimG41UmmL7WhFWeYYg9Dgt6gOBCMR0OTOR+64imFrIRLOgbEQCy7bqZyV\
    g5iDyOOQrLlueTeRnQBMW88Cbj+KNLmHVama/Bj+8ZUN5YZPJwH+sUg4IXFWBbjKpFr\
    upONsJvuOohZoCNCfvlZjcb4/AmsApeD6r2WMwAGv4nuq4TNoBdW3LbP3ajMHjOSd7t\
    oIF5ETaFsPkjdG0SCuf9mgAezTKqqIIO2O5y56eiu3ELRxy/pMKgEe8L2y24ImEIE0z\
    rczFZGRtbg8NrVAX0/8uc6+q7Tv+viAkR9s8kPDea3Q5YNrzKMrWNwDwBh7LGfC+5FX\
    utjEIfyZYrShFuV86kY7Bh5a/hvI4fn5GiglBMLr3+MoUU1dsTdHWTKRZKgR+9dE9wK\
    vWzTycf6azcb3zA48KCyZvV2/t4T69QdsWTst3M2sqhP3E8KkdG9S1Os4RHJvO2Vvfi\
    LTGDjUs6F17S7YqlFNRr4EUj480nebgSL7MHZ6nUr+XR+DU29APbkXllws7aFzkvMD1\
    mqJZYKSP9oVYaUgBCwxrzv9GDqDsO8hRBCjvWrfBvqFc/+zXK9jf96r425+NiDbNKEV\
    V2IH+ji3dzDQjdZ3C+LZquTQ="
    - AWS_DEFAULT_REGION="us-east-2"
    # AWS_SECRET_ACCESS_KEY
    - secure: "AazPelSeZ1V5ZMWPsjPQTh92IQ1F/AT7qyfXGRDpv8xfYH+lDlQyPexC\
    cSAKyLVIzRGYP0bJJKghLvrehvceKsM/ChktMWoaJiXEotf8Vd8QDf52pN5hUeS/JI8\
    3mGbvcox4We66YCj15PkHP4ulAdyrV9JHigVFdnjHucY3/ql/WWV6NHI3/lQXrPfUDm\
    SggYhayDrPSuntXPyc/yHuIy6pNVwsTALgcU4gWgeaHpi8dxaFgf1Vy2S+I3wBZNiCw\
    U9JKhdapNmNzZMRAAfX4eZB6GH+tzPHZbfCvyT4WGxgYPGbPpYpc9ZezYHiquz5ZWp2\
    1vrAxqeogCejkKBCjrddRztKLMsLR4YYoWXithBVMx8aQBRmecekYZE+GkzVpjNnDIH\
    Nyn5I2DbIcFNr4Op1MRb1q8MbAesWKWjCtMsSg3jEfp7ovXZQMnK1Wt54fr5BvlugMv\
    gpeMsof2Ylthm6Mc2w0vrmravGsZuxeilUBdd6dt6rc9Qs5H2pCbNP+qX3OIPZ8MqcD\
    UOr0vI44TyRP5gGhzffCimNxTlL5V0apcmsPWmJfPiSBTlCLgmr/iQqGyTcmzVmtv6B\
    xUlhZIswVyaLgZGoVFLdjyNVN318dgrqVU1XiI4T7neZBPfFSLVIn4sSwi8kHm8/wU4\
    arbZgCc5cAZ88NrGVVH2A/gk="

# Install terraform and terraform-doc
before_install:
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.4/terraform_0.12.4_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - go get github.com/segmentio/terraform-docs

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt
script:
  - pre-commit run --all-files
  - molecule test
