---
- name: Set up VNC as a systemd service
  ansible.builtin.template:
    src: vncserver@.service
    dest: /lib/systemd/system/
    mode: 0644
    validate: /usr/bin/systemd-analyze verify %s

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable VNC systemd service
  ansible.builtin.systemd:
    name: "vncserver@1.service"
    enabled: true
