---
# tasks file for ansible-role-vnc-server

- name: Create the VNC user
  user:
    name: "{{ username }}"
    shell: /bin/bash

- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        # The OS family and distribution for Kali is "Kali GNU/Linux",
        # which is not an allowable file name in Linux due to the
        # slash.  We will allow Kali to fall through and use the
        # Debian vars file.
        - Debian.yml
      paths:
        - "vars"

- name: Install TigerVNC server
  package:
    name:
      "{{ package_names }}"

# Does this go here?  Can this be generalized?
- name: Disable screen locking
  file:
    path: /etc/xdg/autostart/light-locker.desktop
    state: absent

- name: Create .vnc directory for VNC user
  file:
    path: /home/{{ username }}/.vnc
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Set VNC password for VNC user
  shell: |
    set -o pipefail
    echo {{ password }} | vncpasswd -f > /home/{{ username }}/.vnc/passwd
  args:
    executable: /bin/bash
    creates: /home/{{ username }}/.vnc/passwd

- name: Set correct permissions for VNC passwd file
  file:
    path: /home/{{ username }}/.vnc/passwd
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600

- name: Set up VNC as a systemd service
  template:
    src: vncserver@.service
    dest: /lib/systemd/system/
    mode: 0644

- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == "systemd"

- name: Enable VNC systemd service
  systemd:
    name: "vncserver@1.service"
    enabled: true
  when:
    - ansible_service_mgr == "systemd"
